### ISSUE TITLE
How can support more extension of source files?

### ISSUE THREAD

**Issue by cpd92** [mbcrawfo/GenericMakefile#18]
Hi. I am so appreciate to get this makefile template. But when i use it in my project i am confused.Because the extension of source files just can has one formate like "cpp". How can we support more format like "*.cc""*.cpp" in the same time ?  I hope this makefile can support this and thanks a lot!

**Comment by mbcrawfo** [comment]
The way it's written right now the makefile can only support one file extension in a project.  I'm sure it could be modified to support multiple, but I don't know offhand what changes would be needed.  I'm happy to take PR's if you or someone else is interested in adding that feature.

**Comment by cpd92** [comment]
Thanks for your respond. I try but it failed in the current structure. Does multiple extension support in it will decrease the performance? Or different extension file can't compile in the same time just because the object file?

**Comment by ublek** [comment]
Hello, is there anyway i can extend your makefile to compile multiple executables in the src directory using shared code?
i.e
src
-->main1.c
-->main2.c
-->tool
---------->tool.c
----------->tool.h
after compiling we get main1 & main2 executables.

**Comment by mbcrawfo** [comment]
Sorry, I completely forgot about answering this.  Yes, adding more extensions would hurt the performance a bit since searching for the files to compile would be more complex.  I doubt that it would make a noticeable difference unless you had a large project.
