### ISSUE TITLE
can't automatic include *.h 

### ISSUE THREAD

**Issue by ixuhan** [mbcrawfo/GenericMakefile#21]
my folder:
----------
Makefile
main.c
src/
    ->a.c
    ->b.c
inc/
    ->a.h
    ->b.h
---------
when i run make , it remind 'a.h :No such file or directory'
i have to change 'INCLUDES = -I inc/'

how about  include *.h  automatic ?

**Comment by mbcrawfo** [comment]
Hi, I modified the hello world c program included in this repo to use that folder structure and it is compiling for me.  Can you post a full example or link me to a repo that reproduces this problem?

I don't have any plans to add new features to this project, but I'm happy to accept PR's if you would like to implement automatic header resolution.
