### ISSUE TITLE
Mac OS build/link times are not displayed correctly.

### ISSUE THREAD

**Issue by moshohayeb** [mbcrawfo/GenericMakefile#6]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
     Compile time: usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

Linking: bin/release/xxx
     Link time: usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

Making symlink: xxx -> bin/release/xxx
Total build time: usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

**Comment by bumblebritches57** [comment]
Why not just use the time command?
